spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: service-user
          uri: lb://SERVICE-USER
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1
        - id: service-order
          uri: lb://SERVICE-ORDER
          predicates:
            - Path=/api/order/**
          filters:
            - StripPrefix=1
server:
  port: 8200
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
